name: 'Purge Cloudflare cache Action'
description: "Purge a zone's cache via the Cloudflare API"
branding:
  icon: 'cloud'
  color: 'orange'

inputs:
  zone:
    description: "The Zone ID of your domain, which can be found in the right sidebar of your domain's overview page on the Cloudflare dashboard"
    required: true
  api_token:
    description: 'A Cloudflare API Token'
    required: false
  api_key:
    description: 'A Cloudflare API Key'
    required: false
  email:
    description: 'The email address you registered your Cloudflare account with'
    required: false
  files:
    description: 'A space seperated list of URLs to purge'
    required: false
  sitemap:
    description: 'XML sitemap URL. You can use this instead of manually providing a list of files'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
